package com.example.studenttracker.Models;


import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.time.LocalDateTime;

@Entity(tableName = "terms")
public class Term {
    @PrimaryKey(autoGenerate = true)
    private Integer termID; //Autogenerated as PrimaryKey

    private String title;
    private LocalDateTime startDate;
    private LocalDateTime endDate;

  public Term(Integer termID, String title, LocalDateTime startDate, LocalDateTime endDate) {
      this.termID = termID;
      this.title = title;
      this.startDate = startDate;
      this.endDate = endDate;

  }

    public int getTermId() {
        return termID;
    }

    public void setTermId(Integer termId) {
        this.termID = termId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public LocalDateTime getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public LocalDateTime getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

//  I have not used this before.
    @Override
    public String toString() {
        return "Term{" +
                "termId=" + termID +
                ", title='" + title + '\'' +
                ", startDate=" + startDate +
                ", endDate=" + endDate +
                '}';
    }
}
